dbConfig:
  host: "localhost"
  name: "task-distribution-optimizer"
  user: "task-distribution-optimizer"
  password: "task-distribution-optimizer"
  port: 6432

jwtSecret: "harikulade-gizli-key"

serverConfig:
  port: 3000
  readTimeout: 10
  writeTimeout: 10
  idleTimeout: 5
